<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="HollandCRM_Prod_Smoke.SmokeScenarios" tests="4" time="53.895" ignored="0" failures="0" timestamp="30 Nov 2018 17:49:45 GMT" skipped="0" hostname="IS54" errors="1">
  <testcase name="Validate_AccountName_Displayed_AccountListUnderSales4" time="0.308" classname="HollandCRM_Prod_Smoke.SmokeScenarios"/>
  <testcase name="Validate_AccountInformation_Displayed_AccountListUnderSales" time="0.001" classname="HollandCRM_Prod_Smoke.SmokeScenarios">
    <error type="org.testng.TestNGException" message="
Cannot inject @Test annotated Method [Validate_AccountInformation_Displayed_AccountListUnderSales] with [class java.util.Hashtable].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection">
      <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [Validate_AccountInformation_Displayed_AccountListUnderSales] with [class java.util.Hashtable].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:244)
	at org.testng.internal.Parameters.createParameters(Parameters.java:172)
	at org.testng.internal.Parameters.createParameters(Parameters.java:458)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:568)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Validate_AccountInformation_Displayed_AccountListUnderSales -->
  <testcase name="Validate_AccessToAccountListUnderSales" time="50.967" classname="HollandCRM_Prod_Smoke.SmokeScenarios"/>
  <testcase name="Validate_AccountInformation_Displayed_AccountListUnderSales2" time="2.619" classname="HollandCRM_Prod_Smoke.SmokeScenarios"/>
</testsuite> <!-- HollandCRM_Prod_Smoke.SmokeScenarios -->
